#!/usr/bin/env bash
#
# Pure bash implementation of the sha256 checksum algorithm
#
# Usage
#
#   $ ./sha256 file.txt
#   $ ./sha256 < file.bin
#   $ DEBUG=1 ./sha256 < file.bin
#
# # Created
# Author: Dave Eddy <ysap@daveeddy.com>
# Date: July 28, 2026
# License: MIT
#
# # Contributors
# - Dave Eddy <ysap@daveeddy.com>

LC_ALL=C

U32_MASK=0xffffffff

block=()
byte_count=0

# Initialize hash values:
# (first 32 bits of the fractional parts of the square roots of the first 8
# primes 2..19):
h0=0x6a09e667
h1=0xbb67ae85
h2=0x3c6ef372
h3=0xa54ff53a
h4=0x510e527f
h5=0x9b05688c
h6=0x1f83d9ab
h7=0x5be0cd19

# Initialize array of round constants:
# (first 32 bits of the fractional parts of the cube roots of the first 64
# primes 2..311):
k=(
	0x428a2f98 0x71374491 0xb5c0fbcf 0xe9b5dba5
	0x3956c25b 0x59f111f1 0x923f82a4 0xab1c5ed5
	0xd807aa98 0x12835b01 0x243185be 0x550c7dc3
	0x72be5d74 0x80deb1fe 0x9bdc06a7 0xc19bf174
	0xe49b69c1 0xefbe4786 0x0fc19dc6 0x240ca1cc
	0x2de92c6f 0x4a7484aa 0x5cb0a9dc 0x76f988da
	0x983e5152 0xa831c66d 0xb00327c8 0xbf597fc7
	0xc6e00bf3 0xd5a79147 0x06ca6351 0x14292967
	0x27b70a85 0x2e1b2138 0x4d2c6dfc 0x53380d13
	0x650a7354 0x766a0abb 0x81c2c92e 0x92722c85
	0xa2bfe8a1 0xa81a664b 0xc24b8b70 0xc76c51a3
	0xd192e819 0xd6990624 0xf40e3585 0x106aa070
	0x19a4c116 0x1e376c08 0x2748774c 0x34b0bcb5
	0x391c0cb3 0x4ed8aa4a 0x5b9cca4f 0x682e6ff3
	0x748f82ee 0x78a5636f 0x84c87814 0x8cc70208
	0x90befffa 0xa4506ceb 0xbef9a3f7 0xc67178f2
)

# unused: this was inlined for speed
rightrotate() {
	local num=$1
	local rot=$2

	echo "$(( (num >> rot) | (num << (32 - rot)) ))"
}

process-block() {
	# create a 64-entry message schedule array w[0..63] of 32-bit words
	# (The initial values in w[0..63] don't matter, so many implementations
	# zero them here)
	# copy chunk into first 16 words w[0..15] of the message schedule array
	local w=()

	# break chunk into sixteen 4 byte / 32-bit words w[0..15]
	local i j
	for ((i = 0; i < 16; i++)); do
		j=$((i * 4))
		w[i]=$((block[j] << 24 | block[j+1] << 16 |
			block[j+2] << 8 | block[j+3]))
	done

	# Extend the first 16 words into the remaining 48 words w[16..63] of the
	# message schedule array:
	local s0 s1
	for ((i = 16; i < 64; i++)); do
		s0=$((
			(
				((w[i-15] >> 7) | (w[i-15] << (32 - 7))) ^
				((w[i-15] >> 18) | (w[i-15] << (32 - 18))) ^
				(w[i-15] >> 3)
			) & U32_MASK
		))
		s1=$((
			(
				((w[i-2] >> 17) | (w[i-2] << (32 - 17))) ^
				((w[i-2] >> 19) | (w[i-2] << (32 - 19))) ^
				(w[i-2] >> 10)
			) & U32_MASK
		))
		w[i]=$(( (w[i-16] + s0 + w[i-7] + s1) & U32_MASK ))
	done

	# Initialize working variables to current hash value:
	local a=$h0
	local b=$h1
	local c=$h2
	local d=$h3
	local e=$h4
	local f=$h5
	local g=$h6
	local h=$h7

	# Compression function main loop:
	local S1 ch temp1 S0 maj temp2
	for ((i = 0; i < 64; i++)); do
		S1=$((
			((e >> 6) | (e << (32 - 6))) ^
			((e >> 11) | (e << (32 - 11))) ^
			((e >> 25) | (e << (32 - 25)))
		))
		ch=$(( (e & f) ^ ((~e) & g) ))
		temp1=$(( (h + S1 + ch + k[i] + w[i]) & U32_MASK ))
		S0=$((
			((a >> 2) | (a << (32 - 2))) ^
			((a >> 13) | (a << (32 - 13))) ^
			((a >> 22) | (a << (32 - 22)))
		))
		maj=$(( (a & b) ^ (a & c) ^ (b & c) ))
		temp2=$(( (S0 + maj) & U32_MASK ))

		h=$g
		g=$f
		f=$e
		e=$(( (d + temp1) & U32_MASK ))
		d=$c
		c=$b
		b=$a
		a=$(( (temp1 + temp2) & U32_MASK ))
	done

	# Add the compressed chunk to the current hash value:
	h0=$(( (h0 + a) & U32_MASK ))
	h1=$(( (h1 + b) & U32_MASK ))
	h2=$(( (h2 + c) & U32_MASK ))
	h3=$(( (h3 + d) & U32_MASK ))
	h4=$(( (h4 + e) & U32_MASK ))
	h5=$(( (h5 + f) & U32_MASK ))
	h6=$(( (h6 + g) & U32_MASK ))
	h7=$(( (h7 + h) & U32_MASK ))
}

process-byte() {
	local byte=$1

	debug "process-byte($byte)"

	# store the byte
	block+=("$byte")

	# check if we have a full block ready for processing
	if ((${#block[@]} == 64)); then
		process-block
		block=()
	fi
}

process-input() {
	local chunk i c

	while true; do
		IFS= read -r -d '' -n 4096 chunk
		local code=$?
		local n=${#chunk}

		debug "read $n bytes (code=$code)"

		# loop the chunk and process byte-by-byte
		for ((i = 0; i < n; i++)); do
			c=${chunk:i:1}
			printf -v c '%d' "'$c"
			process-byte "$c"
			((byte_count++))
		done

		# `read` failed - so we are done processing
		if ((code != 0)); then
			break
		fi

		# check for nul
		if ((n < 4096)); then
			process-byte 0
			((byte_count++))
		fi
	done

	# we've read the entire message - now we have to finalize it by padding
	# it and appending the length

	# pad it with 1 and then a bunch of 0s
	process-byte 0x80
	while (( ${#block[@]} != 56 )); do
		process-byte 0
	done

	# append original length in bits mod 2^64 to message
	# turn the byte length into 2 numbers - high bits and low bits
	local low_bits=$(( (byte_count << 3) & U32_MASK))
	local high_bits=$(( (byte_count >> (32 - 3)) & U32_MASK ))

	# encode the full 64bit int (bits length) as big endian
	local byte
	for ((i = 3; i >= 0; i--)); do
		byte=$(( high_bits >> (i * 8) & 0xff ))
		debug "high_bits[$i]=$byte"
		process-byte "$byte"
	done
	for ((i = 3; i >= 0; i--)); do
		byte=$(( low_bits >> (i * 8) & 0xff ))
		debug "low_bits[$i]=$byte"
		process-byte "$byte"
	done

	# assert things are correct
	if (( ${#block[@]} != 0 )); then
		echo 'uh oh! something went wrong' >&2
		exit 1
	fi
}

debug() {
	if [[ -n $DEBUG ]]; then
		echo '[DEBUG]' "$@" >&2
	fi
	return 0
}

print-hash() {
	printf '%08x' "$h0" "$h1" "$h2" "$h3" "$h4" "$h5" "$h6" "$h7"
	echo
}

main() {
	local file=$1

	if [[ -n $file ]]; then
		debug "reading data from file: $file"
		process-input < "$file" || return 1
	else
		debug "reading data from stdin"
		process-input
	fi

	print-hash
}

main "$@"
